/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as SuperAdminClientControlRouteImport } from './routes/super-admin.client-control'
import { Route as DashboardRecipesRouteImport } from './routes/dashboard.recipes'
import { Route as DashboardPurchasesRouteImport } from './routes/dashboard.purchases'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminClientControlRoute = SuperAdminClientControlRouteImport.update({
  id: '/super-admin/client-control',
  path: '/super-admin/client-control',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecipesRoute = DashboardRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPurchasesRoute = DashboardPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/super-admin/client-control': typeof SuperAdminClientControlRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/super-admin/client-control': typeof SuperAdminClientControlRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/recipes': typeof DashboardRecipesRoute
  '/super-admin/client-control': typeof SuperAdminClientControlRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/performance'
    | '/dashboard/purchases'
    | '/dashboard/recipes'
    | '/super-admin/client-control'
    | '/super-admin/login'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/performance'
    | '/dashboard/purchases'
    | '/dashboard/recipes'
    | '/super-admin/client-control'
    | '/super-admin/login'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/performance'
    | '/dashboard/purchases'
    | '/dashboard/recipes'
    | '/super-admin/client-control'
    | '/super-admin/login'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SuperAdminClientControlRoute: typeof SuperAdminClientControlRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/client-control': {
      id: '/super-admin/client-control'
      path: '/super-admin/client-control'
      fullPath: '/super-admin/client-control'
      preLoaderRoute: typeof SuperAdminClientControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/recipes': {
      id: '/dashboard/recipes'
      path: '/recipes'
      fullPath: '/dashboard/recipes'
      preLoaderRoute: typeof DashboardRecipesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/purchases': {
      id: '/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof DashboardPurchasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardPurchasesRoute: typeof DashboardPurchasesRoute
  DashboardRecipesRoute: typeof DashboardRecipesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardPurchasesRoute: DashboardPurchasesRoute,
  DashboardRecipesRoute: DashboardRecipesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SuperAdminClientControlRoute: SuperAdminClientControlRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
